### PR TITLE
Expose methods for getting the raw results of a query

### PR DESCRIPTION
**Pull request by ebarendt**
For some upcoming features, I would like to access the raw ES results.

It will help with:
1) Finding search scores
2) Getting the name of the query that matched

### CODE REVIEW

**Comment by ebarendt** [comment]
Alternately: introduce some objects to wrap the raw responses.

**Comment by matthuhiggins** [comment]
Seems fine

I think it's premature to wrap with an object. Are you thinking of something like `ActiveRecord::Result`?

**Comment by ebarendt** [comment]
Something like that maybe. But I'd also want the Results wrapped in something because there's info there (like max_score). I think raw is the way to go for now.

**Comment by matthuhiggins** [comment]
A result object should be lightweight.

**Pull request merged**
