### PR TITLE
Helper method for saving to ES

### PR DESCRIPTION
**Pull request by ebarendt**

### CODE REVIEW

**Comment by matthuhiggins** [comment]
Would this call callbacks, or is this used within the callback?

**Comment by ebarendt** [comment]
I thought about calling it from [here](https://github.com/data-axle/elastic_record/blob/e06b3b6e35d68172133c9b6f1835500159376d1b/lib/elastic_record/callbacks.rb#L16).

**Comment by matthuhiggins** [comment]
That makes sense. I think we also need one that calls callbacks, which is out of scope here.

For that reason, a different name such as `index_to_elasticsearch` is more clear, and leaves room for a save that performs callbacks.

**Comment by ebarendt** [comment]
Updated.

**Pull request merged**
